version: "3.3"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  db:
    image: postgres:10.6
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
